dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install -y libdiscid0
  - sudo apt-get install -y libdbus-glib-1-dev

# command to run tests
script:
  - python setup.py test
