dist: xenial

language: python

python:
  - "3.6"
  # - "3.7"
  # PyPy versions
  # - "pypy3.5"

before_install:
  - sudo apt-get install -y libdiscid0

# command to run tests
script:
  - python setup.py install
  - python setup.py test
