# Travis Continuous Integration Configuration File

language: python

dist: xenial

os:
  - linux
#  - osx # python 3.6/3.7 are not supported on the osx build environment
#  - windows # python is currently unsupported on the Windows Build Environment

python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - libdiscid0
      - libdbus-glib-1-dev

# command to run tests
script:
  - python setup.py test
